#cloud-config
users: #Die zu erstellenden Benutzer
  - name: ubuntu #Der Benutzername des Nutzers
    sudo: ALL=(ALL) NOPASSWD:ALL #Die Sudo regeln die verwendet werden für den User
    groups: users, admin #Die gruppen in welche der User gesteckt wird
    home: /home/ubuntu #Das home verzeichnis des Users
    shell: /bin/bash #Die standart shell des users
    lock_passwd: false #Definiert ob der User sein passwort ändern kann oder nicht
    plain_text_passwd: 'password' #Das Passwort des Users        
ssh_pwauth: true #Gibt an ob eine Passwort authentifizierung benötigt wird bei einer SSh conection
disable_root: false #Definiert ob das root login aktiviert oder deaktiviert ist
packages: #Die packages die vor-installiert werden sollen
  - apache2 
  - curl 
  - wget 
  - php 
  - libapache2-mod-php 
  - php-mysqli
  - adminer

package-update: true
package_upgrade: true

write_files:
- content: |
    <?php
    // Show all information, defaults to INFO_ALL
    phpinfo();
    ?>
  path: /var/www/html/info.php
  permissions: "0644"

- content: |
    <?php
        //database
        $servername = "127.0.0.1";
        $username = "admin";
        $password = "password";
        $dbname = "mysql";

        // Create connection
        $conn = new mysqli($servername, $username, $password, $dbname);
        // Check connection
        if ($conn->connect_error) {
                die("Connection failed: " . $conn->connect_error);
        }

        $sql = "select Host, User from mysql.user;";
        $result = $conn->query($sql);
        while($row = $result->fetch_assoc()){
                echo($row["Host"] . " / " . $row["User"] . "<br />");
        }
        //var_dump($result);
    ?>

  path: /var/www/html/db.php
  permissions: "0644"

  runcmd:
  - "chown ubuntu:ubuntu /var/www/html/info.php /var/www/html/db.php"
  - "sudo a2enconf adminer"
  - "sudo systemctl restart apache2"