#cloud-config
users: #Die zu erstellenden Benutzer
  - name: ubuntu #Der Benutzername des Nutzers
    sudo: ALL=(ALL) NOPASSWD:ALL #Die Sudo regeln die verwendet werden für den User
    groups: users, admin #Die gruppen in welche der User gesteckt wird
    home: /home/ubuntu #Das home verzeichnis des Users
    shell: /bin/bash #Die standart shell des users
    lock_passwd: false #Definiert ob der User sein passwort ändern kann oder nicht
    plain_text_passwd: 'password' #Das Passwort des Users  
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDlFlyfKULouLkuyZXTwwCHoA9Db2OnGTpTaxz25U3+jDFxSRP/MtxUEDvCFXoZq+WtE3pQyVnDOjR8uzKgcUz4CADce3tqt1VLWaxTt+yw9uYSNnKdNbnCwbmGwXFCXiBL3iMDyYgbhPpxBhGO3WLS+YKcMYNQzvq4X8KCSqKdBIRdQeG9QcYZULoPYRJbY0y2Q9RRDZ+QfzXnCBHumA2kQRLa8twzJzgrKxkQctiVdHNBZCOxhQ1DvO3WhLt/fdy1Pcwk4G98GmFUYbgG6y0rCFRYZEQKJyf0393S22bwCp3V1vE3cMRhmARHwcTdrfzhKDrUfW8siLWx6smAQQT8+UBbAQyn+bdWL7UpOxwBffPqzzT46LM8Qn7FXNK+qHg1EH/Br5UGmntk0mc7PkybKCc/xVGpbxbvdDqccEqn9jTQI2rakZAaxXMEgcIjyoesWmF1/mh6z+djqTWS/XuFtVWYbanolrQ5rMeMUYfK1r2M+F96z+5HJTpMddkLsjs= mikka.kummer@noseryoung.com
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD aws-key
ssh_pwauth: true #Gibt an ob eine Passwort authentifizierung benötigt wird bei einer SSh conection
disable_root: false #Definiert ob das root login aktiviert oder deaktiviert ist
package_update: true
packages: #Die packages die vor-installiert werden sollen
  - apache2 
  - curl 
  - wget 
  - php 
  - libapache2-mod-php 
  - php-mysqli
  - adminer
package_upgrade: true

write_files:
- content: |
    <?php
    // Show all information, defaults to INFO_ALL
    phpinfo();
    ?>
  path: /var/www/html/info.php
  permissions: "0644"
- content: |
    <?php
        //database
        $servername = "172.31.10.101";
        $username = "admin";
        $password = "password";
        $dbname = "mysql";

        // Create connection
        $conn = new mysqli($servername, $username, $password, $dbname);
        // Check connection
        if ($conn->connect_error) {
                die("Connection failed: " . $conn->connect_error);
        }

        $sql = "select Host, User from mysql.user;";
        $result = $conn->query($sql);
        while($row = $result->fetch_assoc()){
                echo($row["Host"] . " / " . $row["User"] . "<br />");
        }
        //var_dump($result);
    ?>

  path: /var/www/html/db.php
  permissions: "0644"

  runcmd:
  - sudo a2enconf adminer
  - sudo systemctl restart apache2